@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

abstract EntityList
interface ReadableEntityList <<Interface>>

Model *-down-> "1" ParticipantList
Model *-down-> "1" MentorList
Model *-down-> "1" TeamList

EntityList .right.|> ParticipantList
EntityList .down.|> TeamList
EntityList .down.|> MentorList

ReadableEntityList .down.|> ParticipantList
ReadableEntityList .down.|> TeamList
ReadableEntityList .down.|> MentorList

ParticipantList *-down-> "*" Participant
MentorList *-down-> "*" Mentor
TeamList *-down-> "*" Team

@enduml
